services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 5000:5000
    command: npm run dev
    volumes:
      - /app/server/node_modules
      - ./server:/app/server

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 5173:5173
    command: npm run dev
    volumes:
      - /app/client/node_modules
      - ./client:/app/client

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: